[tool.poetry]
name = "ingestion-framework"
version = "0.0.24"
description = "Config driven Data Ingestion Framework"
authors = ["Krijn van der Burg"]
readme = "README.md"
packages = [{ include = "ingestion_framework", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
pyspark = "^3.5.0"
pandas = "^2.2.0"
pyarrow = ">=4.0.0,<17.0.0" # Support pyarrow 4.x.x
pyyaml = "^6.0.1"
numpy = "<2.0.0"

[tool.poetry.group.test.dependencies]
pytest = ">=8.3.0"
pytest-cov = ">=2.0.0"
pytest-xdist = ">=3.6.1"
setuptools = "^74.1.2"

[tool.poetry.group.cicd.dependencies]
requests = "^2.26.0"
types-requests = "^2.26.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
